# Generated by Django 5.1.1 on 2024-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Admin'), ('frentista', 'Frentista')], max_length=10)),
            ],
        ),
    ]
