# Generated by Django 5.1.1 on 2024-09-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
