# Generated by Django 5.1.1 on 2024-09-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0003_veiculo_abastecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='App_Combustivel.veiculo'),
        ),
    ]
