# Generated by Django 5.1.1 on 2024-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0004_alter_abastecimento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='km_anterior',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='quantidade_abastecida',
            field=models.FloatField(default=0),
        ),
    ]
