# Generated by Django 5.1.1 on 2024-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0005_abastecimento_km_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
