# Generated by Django 5.1.1 on 2024-09-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0006_alter_abastecimento_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='modelo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='km_anterior',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='quantidade_abastecida',
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Combustivel.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
