# Generated by Django 5.1.1 on 2024-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0007_rename_modelo_veiculo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
