# Generated by Django 5.1.1 on 2024-09-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0010_remove_usuario_email_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='pedo@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
