# Generated by Django 5.1.1 on 2024-09-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0011_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
