# Generated by Django 5.1.1 on 2024-09-21 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0012_remove_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='App_Combustivel.usuario'),
            preserve_default=False,
        ),
    ]
