# Generated by Django 5.1.1 on 2024-09-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0016_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
