# Generated by Django 5.1.4 on 2025-01-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0017_alter_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='media_prevista',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='nome',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveIntegerField(default=2010, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.CharField(default=1010, max_length=50, unique=True, verbose_name='Ativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassis',
            field=models.CharField(default=10101010, max_length=50, unique=True, verbose_name='Chassis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='equipamento',
            field=models.CharField(default=1, max_length=100, verbose_name='Equipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default=5, max_length=50, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=89, max_length=50, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='obra',
            field=models.CharField(default=1, max_length=100, verbose_name='Obra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Placa'),
        ),
    ]
