# Generated by Django 5.1.4 on 2025-01-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0018_remove_veiculo_media_prevista_remove_veiculo_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLubrificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('data', models.DateField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Combustivel.veiculo')),
            ],
        ),
    ]
