# Generated by Django 5.1.4 on 2025-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0019_consumolubrificante'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='media_prevista',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
