# Generated by Django 5.1.4 on 2025-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0020_veiculo_media_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_dif_dianteiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Dif. Dianteiro (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_dif_traseiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Dif. Traseiro (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_direcao',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Direção (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_hidraulica',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Hidráulica (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_motor',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Motor (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_transmissao',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimativa Troca Óleo Transmissão (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_dif_dianteiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Dif. Dianteiro (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_dif_traseiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Dif. Traseiro (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_direcao',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Direção (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_hidraulica',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Hidráulica (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_motor',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Motor (km)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_transmissao',
            field=models.PositiveIntegerField(default=0, verbose_name='Última Troca Óleo Transmissão (km)'),
        ),
    ]
