# Generated by Django 5.1.4 on 2025-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0021_veiculo_estimativa_dif_dianteiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_dif_dianteiro',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_dif_traseiro',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_direcao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_hidraulica',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_motor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estimativa_transmissao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ultima_troca_dif_dianteiro',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ultima_troca_dif_traseiro',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ultima_troca_direcao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ultima_troca_hidraulica',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ultima_troca_transmissao',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_motor',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ultima_troca_motor',
            field=models.IntegerField(default=0),
        ),
    ]
