# Generated by Django 5.1.4 on 2025-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0022_remove_veiculo_estimativa_dif_dianteiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_dif_dianteiro',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_dif_traseiro',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_direcao',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_hidraulica',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estimativa_troca_transmissao',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_dif_dianteiro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_dif_traseiro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_direcao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_hidraulica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_troca_transmissao',
            field=models.IntegerField(default=0),
        ),
    ]
