# Generated by Django 5.1.4 on 2025-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0023_veiculo_estimativa_troca_dif_dianteiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_dif_dianteiro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_dif_traseiro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_direcao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_hidraulica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_motor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='estimativa_troca_transmissao',
            field=models.IntegerField(),
        ),
    ]
