# Generated by Django 5.1.4 on 2025-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0024_alter_veiculo_estimativa_troca_dif_dianteiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumolubrificante',
            name='quilometragem',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
