# Generated by Django 5.1.4 on 2025-01-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0025_consumolubrificante_quilometragem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossieManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_parada', models.DateField()),
                ('data_liberacao', models.DateField(blank=True, null=True)),
                ('horimetro_acumulado', models.IntegerField()),
                ('defeito_apresentado', models.IntegerField()),
                ('causa_falha', models.TextField()),
                ('servico_executado', models.TextField()),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_osi', models.CharField(max_length=255)),
                ('executado_por', models.CharField(max_length=255)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossies', to='App_Combustivel.veiculo')),
            ],
        ),
    ]
