# Generated by Django 5.1.4 on 2025-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0026_dossiemanutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiemanutencao',
            name='defeito_apresentado',
            field=models.CharField(max_length=255),
        ),
    ]
