# Generated by Django 5.1.4 on 2025-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0027_alter_dossiemanutencao_defeito_apresentado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumolubrificante',
            name='tipo_oleo',
            field=models.CharField(default=1540, max_length=50),
            preserve_default=False,
        ),
    ]
