# Generated by Django 5.1.4 on 2025-01-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0028_consumolubrificante_tipo_oleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem_total',
            field=models.FloatField(default=0),
        ),
    ]
