# Generated by Django 5.1.4 on 2025-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Combustivel', '0029_veiculo_quilometragem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_consumo',
            field=models.CharField(choices=[('quilometragem', 'Quilometragem'), ('horimetro', 'Horímetro')], default='quilometragem', max_length=20),
        ),
    ]
